from brochure.values.enterprise import Enterprise
from brochure_reference_implementations.named_tuple_fetcher_provider import NamedTupleFetcherProvider

ReferenceEnterpriseFetcher = NamedTupleFetcherProvider(named_tuple_type=Enterprise)
