from brochure.values.contact_method import ContactMethod
from brochure_reference_implementations.named_tuple_fetcher_provider import NamedTupleFetcherProvider

ReferenceContactMethodFetcher = NamedTupleFetcherProvider(named_tuple_type=ContactMethod)
