#!/usr/bin/env bash


function eval_in_virtual_environment {
    command -v python3 >/dev/null 2>&1 || { echo >&2 "\`python3\` is required, please install it with \`brew install python3\`.  Aborting."; exit 1; }
    command -v virtualenv >/dev/null 2>&1 || { echo >&2 "\`virtualenv\` is required, please install it with \`pip3 install virtualenv\`.  Aborting."; exit 1; }

    VIRTUALENV_NAME=env
    if [ ! -d ${VIRTUALENV_NAME} ]; then
      virtualenv ${VIRTUALENV_NAME} -p python3
    fi

    source ${VIRTUALENV_NAME}/bin/activate

    pip install --upgrade pip > /dev/null 2>&1
    pip install --upgrade wheel > /dev/null 2>&1

    echo "Running '$1' inside virtual environment…"
    $1
}
